### PR TITLE
lineageos: 2020-12-01 update

### PR DESCRIPTION
**Pull request by Atemu**

### CODE REVIEW

**Comment by danielfullmer** [comment]
Build and briefly tested working in the emulator.

**Comment by Atemu** [comment]
Oh, should've mentioned that I built and tested this on cheeseburger too of course :)

**Comment by hmenke** [comment]
@Atemu What is actually the Lineage OS release cycle?  On https://download.lineageos.org/ it looks like there are weekly builds.  Could you please write docs on how to update Lineage OS in Robotnix?  Or maybe you could even write a GitHub Action which automatically opens PRs for Lineage OS updates.

**Comment by Atemu** [comment]
Their release cycle is "whatever's currently on HEAD of these 800 git repos: <list/>" I think. They build the current version nightly and the previous weekly.

In Robotnix, There's an update.sh that sort of works IME but you can also just run the python scripts manually. After running either, you also have to bump the one UNIX timestamp in default.nix with the current `date +%s`.

There's currently an issue with one the Google/Asus Flox that prevents the device-dirs script from workig which I've been meaning to look into but haven't gotten around to.

**Pull request merged**
