### PR TITLE
Small docs fixes based on a Pixel 4a GrapheneOS install experience

### PR DESCRIPTION
**Pull request by mschwaig**
I recently went through the process of building GrapheneOS using Robotnix and installing it on a Pixel 4a and made some improvements to the documentation based on that experience.

I have put my changes into separate commits, because I thought you might want to have some but not all of them.

### CODE REVIEW

**Comment by danielfullmer** [comment]
Thanks. These changes look good to me.  My only change would be to add the following to point (8):

> However, if you later lose the ability to re-enable OEM unlocking (potentially by pushing a bad update that you cannot rollback or update otherwise), you will be unable to flash a new image to your device.

**Comment by mschwaig** [comment]
Could this happen from only  losing the ability to re-enable OEM unlocking or would you also have to lose access to your signing key?

I'm not too familiar with those flashing tools, but I imagine you could always still push a working update via fastboot as long as you can still use the same signing key. 🤔

> Thanks. These changes look good to me. My only change would be to add the following to point (8):
> 
> > However, if you later lose the ability to re-enable OEM unlocking (potentially by pushing a bad update that you cannot rollback or update otherwise), you will be unable to flash a new image to your device.

**Comment by danielfullmer** [comment]
It's not entirely clear to me either.  Luckily I've never had to encounter this issue :).  If you can still get to recovery and sideload a signed update, then I'd expect you could recover from that.  But, perhaps the ability to get into recovery and sideload an update might get broken by a bad update too....

How about this alternative?
> However, if you later lose the ability to re-enable OEM unlocking (potentially by pushing a bad update that you cannot rollback), and have also lost your signing keys, you will be unable fix your device by sideloading a signed update, or by flashing a new image.

**Comment by mschwaig** [comment]
I reworded that 2nd version you posted.

> Note that if you later lose the ability to re-enable OEM unlocking, for example by pushing a bad update that you cannot rollback, and you cannot push another working update because you also lost your signing keys, you might not even be able to recover your device by flashing a stock image, effectively bricking the device.

It's a difficult risk to point out, because it's so device-dependent and hard to look up.
At least [that one XDA Developers thread about ArcaneOS suggests that it might be possible to recover from that kind of a situation](https://forum.xda-developers.com/t/is-it-bricked-cannot-flash-stock-android-to-remove-arcaneos.4285827/). On the other hand the risk of leaving a phone OEM-unlocked is also very difficult for me to quantify.

**Comment by danielfullmer** [comment]
Looks good to me, thanks for the documentation contribution!

**Pull request merged**
