### PR TITLE
lineageos: 2021102406 -> 2022010122

### PR DESCRIPTION
**Pull request by samueldr**
~~Waiting on builds to finish.~~

### CODE REVIEW

**Comment by danielfullmer** [comment]
I won't have convenient access to main machine to build/test this myself for the next few days.  However, this commit looks good to me, and I'm happy to merge it when you can confirm that it builds and boots for you.  In a few days, i'd then push out a signed tag for this when I'm able to test this myself.

**Comment by samueldr** [comment]
> **Basic Tests / nix-instantiate (pull_request)** Failing after 44m — nix-instantiate

¯\\\_(ツ)\_/¯

**Comment by samueldr** [comment]
From limited testing on my two target devices (aura, begonia), things are working just as well as they did for lineageos-18.1

**Comment by danielfullmer** [comment]
> > **Basic Tests / nix-instantiate (pull_request)** Failing after 44m — nix-instantiate
> 
> ¯\_(ツ)_/¯

It's been broken like this for a few weeks. It might be exceeding memory limits or something. I feel the same way: ¯\_(ツ)_/¯  Hope to have time to work on it soon.

**Pull request merged**
