### PR TITLE
Documentation for OTA updates

### PR DESCRIPTION
**Pull request by hmenke**
I finally finished the OTA docs I promised some time ago.  During my experiments with Robotnix on bacon I have also noticed that the updater does not work with LineageOS.  First of all `apps.updater.enable = true;` conflicts with the Lineage updater, but this can be disabled using `source.dirs."packages/apps/Updater".enable = false;` and Robotnix will build successfully.  Unfortuantely, the updater will still not work then.  It downloads the update but when trying to install it, it will just download the update again. (I think.  It could also be that it pretends that it installed but after rebooting it will start downloading the update again.  I don't remember exactly what it did, but it definitely didn't work.)

Rendered: https://github.com/hmenke/robotnix/blob/docs/docs/ota.md

Additionally I have added sunfish to the list of tested devices in the README, since I am using the GrapheneOS flavor as my daily driver for a couple of months now.  If understood it correctly @petabyteboy is also using Robotnix with the Vanilla flavor on sunfish.

### CODE REVIEW

**Comment by ajs124** [comment]
I'm running GrapheneOS on my sunfish as well. Although I'm not testing it too well, considering I'm barely leaving the house in these circumstances. Might end up switchting to vanilla, but either way, one more data point.

**Comment by samueldr** [comment]
> Unfortuantely, the updater will still not work then. It downloads the update but when trying to install it, it will just download the update again. (I think. It could also be that it pretends that it installed but after rebooting it will start downloading the update again. I don't remember exactly what it did, but it definitely didn't work.)

Does the same OTA update work when `adb sideload`'d through the LineageOS recovery?

It may be that LineageOS uses different commands in the BCB to ask the bootloader or the recovery to be done on reboot. Furthermore, if testing against an A/B device, I don't know if they support any upstream, and if they do, if "our" updater would do the right thing here. I do wonder if A/B device updates happen in recovery, or behind the scenes.

(We can / should move this discussion about updater+lineageos in its own issue I guess.)

**Comment by petabyteboy** [comment]
I use vanilla on sunfish. I don't have the updater app, but I use `adb sideload` and that works fine.

**Comment by danielfullmer** [comment]
My expectation was that we could just use the LineageOS updater for LineageOS builds, instead of the one from GrapheneOS.    The update metadata is a bit different, and we'd need to have Robotnix be able to conditionally output an `otaDir` that would work for LineageOS if enabled.

**Pull request merged**
