### PR TITLE
[WIP] DO NOT MERGE — Add LineageOS ROM support

### PR DESCRIPTION
**Pull request by samueldr**
If you were to use `-A img`, the produced zip is "wrong"...

```
~/.../robotnix/pioneer-img-2020.05.04 130 $ fastboot update -w /nix/store/20230ryy6fw9nmrqmzza4zlmmwyrb1cc-pioneer-img-2020.05.04.zip
extracting android-info.txt (0 MB) to RAM...
--------------------------------------------       
Bootloader Version...: 1310-0301_X_Boot_SDM630_LA3.0_P_35
Baseband Version.....: 1311-2921_50.2.A.0.400
Serial Number........: CQ3000V9GR
--------------------------------------------       
Checking product                                   FAILED

Device product is 'H3123'.
Update requires 'sdm660'.

fastboot: error: requirements not met!
```

**If** we want to use *whatever process you do to the zip*, this'll need to be figured out.

Now, when using that zip's contents and using `fastboot flash` it failed. I don't know why. I'm waiting on an `mka bacon` output to see if **that** will boot...

Note that I haven't verified that a lineageos 17.0 product should boot on `pioneer`, but did a 17.1. Don't ask why I did 17.0 here, it's a mistake I think.

 * * *

# TODO

 * [x] Re-generate and test with 17.1
 * [x] Add "roomservice" equivalent script to output device specific repos
 * [ ] Remove/Fix all hacks

### CODE REVIEW

**Comment by danielfullmer** [comment]
I've pushed a couple commits to master which affect this:

1) https://github.com/danielfullmer/robotnix/commit/8f2f3329e743f68294e063f8c3570aafeb969602 With this, we should set `productNamePrefix = "lineage"` if we are `flavor="lineageos"`.  So `productName` ends up something like `lineage_marlin`.  Potentially other flavors in the future will follow a similar structure. I know CalyxOS at least uses `caylx_` or `calyxos_` prefix.

2) https://github.com/danielfullmer/robotnix/commit/46793353715317dbe65d6efd651439d3e1889899 This was actually the cause of the `binder` failures you'd experienced on the Pixel 2 a while back. I was unconditionally overriding the webview, even if I didn't have any valid robotnix-provided webview.

The emulator for `lineage_x86` partially works as well. It boots up, but the launcher is stuck saying "Phone is starting". I could still access settings and start apps through the settings menu.

This list looks very convenient: https://github.com/LineageOS/hudson/blob/master/updater/device_deps.json Maybe it would be sufficient to make a script scraping this json and running `nix-prefetch-git` to make a structure that could fill out `source.dirs` conditionally depending on the device. I count 379 unique repos from that. (totally managable, haha). I'm hoping there aren't many device-specific workarounds required, and we can just programmatically add support for all those devices at once.

As far as fetching proprietary blobs for LineageOS, I see have two options: the infamous github repo containing everything, or [these instructions](https://wiki.lineageos.org/extracting_blobs_from_zips.html).  I personally think the best option is to extract them from a vendor-provided image, but I'm not sure if the linked instructions work with an original vendor image, or require a LineageOS image.  However, that whole approach would seem to require more work for each device. But using the "infamous repo" would allow us to add support for a whole bunch of devices at once.

**Comment by samueldr** [comment]
For blobs, we should do our own *roomservice* equivalent mapping to these:

 * https://github.com/TheMuppets/

Unless that's what that "infamous" repo you were talking about is?

As far as extracting from a vendor image? It might not be good. Some devices are using non-device-specific proprietary blobs on LineageOS! Most of the time it's newer blobs from other devices for the same major Android revision, but I believe it also happened that blobs from other devices were borrowed to port forward one major android version.

**Comment by danielfullmer** [comment]
Yeah, that's the repo I'm referring to. I didn't realize the vendor blobs came from such diverse sources, and based on what you said, it would sounds like there is a significant amount of work done for individual devices that I'd prefer to not have to replicate.  It's just unfortunate to have to trust those blobs when their origin is unclear, and the organizational structure (including who has commit access, and on what basis) is left ambiguous . (Maybe intentionally for legal reasons? I couldn't find much online)

Before advertising LineageOS support, I'll probably write some documentation comparing this with the situation for vanilla AOSP / GrapheneOS, where I use android-prepare-vendor to extract those files from an image directly from Google. Besides reproducibility, one of my broad goals is to ensure our build inputs are authentic. e.g. At some point, I'd also like to check the git tag signatures on the AOSP sources I download, for additional safety beyond TOFU.

**Comment by samueldr** [comment]
Yes! I'm, myself, preparing notes for a set of personal blog post about security, trust, and tinkering. I would call the AOSP and GrapheneOS trustable, verifiable, builds (as long as you trust those blobs). LineageOS builds are less trustable because of those binary blobs that do not match the originals. Though I like when a project puts it front and center where you have to start using trust, and what it means.

I think it would be interesting for the LineageOS project to produce a "pedigree" of sorts, a document of all repos->git hash used as inputs for their ROM builds, so one can independently verify them. I don't know how helpful `robotnix` could be in prodding them in that direction.

**Comment by samueldr** [comment]
*closing as it's obviously being superceded by #9*

**Pull request closed without merging**
