### PR TITLE
LineageOS support

### PR DESCRIPTION
**Pull request by danielfullmer**
Based on https://github.com/danielfullmer/robotnix/pull/8. CC @samueldr

Added a python script to use information from https://github.com/LineageOS/hudson to populate some json files which we can then use to add to `source.dirs`, like `roomservice`. It should (hopefully) have the ability to build any of the `lineage-17.1` devices here: https://github.com/LineageOS/hudson/blob/master/lineage-build-targets
(btw, are the default LineageOS builds all userdebug? Security :worried: if so. Should we have the default be `userdebug` just for lineageOS then?)

I've successfully built the following:
```
nix-build ./default.nix --arg configuration '{device="marlin"; flavor="lineageos";}' -A build.bacon
nix-build ./default.nix --arg configuration '{device="pioneer"; flavor="lineageos";}' -A build.bacon
``` 
Tested the resulting `marlin` ROM briefly as well.

Still need to investigate OTA stuff, including updater/keys/etc. I'm not sure the `build.bacon` target is absolutely necessary, since it just looks to be producing an unsigned OTA image, and it'd be better if it was consistent with the OTA generation for `vanilla`.

A quality-of-life thing: I still seem to be having an issue where the `nix-prefetch-git` used in `update-devices.py` produces an output which is not reused when I run `nix-build`. It works, but I end up fetching the source twice.

We will also need to work out how often we should update our sources, who is responsible for doing so, whether testing is necessary, etc. If I can get better incrementalism in the scripts, it might even be possible to automate updates on some interval.

---

Tasks remaining:
- [x] Add `bootImg` target which pulls `boot.img` out of (optionally signed) `targetFiles` in `release.nix`
- [ ] Add assertions on modules that are unlikely to work with `LineageOS` e.g. `kernel.nix`, `google.nix`, `vendor.nix`, `auditor`, (maybe others?)
- [x] Clean up commit history
- [x] Check if LineageOS 17.1 uses APEX keys: they flatten the APEX packages
- [ ] Fix `avbFlags` in `release.nix` for devices that don't use AVB
- [ ] Documentation

Nice to have, but not necessary before merging:
- [ ] Make LineageOS updater work.
Setting `resources."packages/apps/Updater".updater_server_url = "https://daniel.fullmer.me/android/lineageos";` works to change the URL, but still need to generate metadata for `otaDir`, and verify it actually works.
- [x] Make `update-devices.py` incremental by running `git ls-remote` on tag/branch to check if the revision is newer than the one we currently have
- [ ] Have an option in `update-devices.py` to update just a particular device.
- [ ] Lineage 16.0 support
- [ ] Replace update script with a recursive version like `roomservice` instead of relying on `hudson`
- [x] Test MicroG, custom chromium webview, seedvault (backup)
- [ ] Replace `prebuilts/tools-lineage` with nixpkgs equivalents
- [x] Fix reproducibility issues with bootanimation.zip and kernel

### CODE REVIEW

**Comment by danielfullmer** [comment]
It should now be possible to produce an OTA which can be sideloaded using `adb sideload ...` with `-A ota`.
I've also tested signed builds on `marlin`, and it appears to be working.

I still need to make a target for getting the `boot.img` which can be flashed first using `fastboot`, to then allow a user to sideload the ota. At least, that's my understanding of how lineage is intended to be flashed.  `fastboot update` actually worked for me on marlin.

**Comment by samueldr** [comment]
An `eng` variant OTA for `pioneer` was just built and booted successfully. I did `eng` first because my PR's builds wouldn't boot, so I wanted to finally get a logcat in...

Just saying, though I didn't doubt it much, F-Droid embedding works just fine. 

Now I have queued a `user` build, using `-A img` to confirm, but I suspect it should work, **except** maybe for the device identifier issue. I'll end up splitting the zip open and fastboot flashing the components if it's the case. It may be an issue for more than pioneer, especially for builds that end up supporting more than one device ID.

**Comment by danielfullmer** [comment]
So I ran `build.checkAndroid` against all the `lineage-17.1` devices, to at least see if the build process would work. Here are the devices which succeeded:

```
"Amber" "bardock" "bardockpro" "beryllium" "chef" "cheryl" "chiron" "crownlte"
"d800" "d801" "d802" "d803" "d850" "d851" "d852" "d855" "dipper" "discovery"
"enchilada" "evert" "FP2" "f400" "fajita" "guacamole" "griffin" "gts4lvwifi"
"h830" "h850" "h910" "h918" "h990" "I01WD" "jactivelte" "jflteatt" "jfltespr"
"jfltevzw" "jfltexx" "jfvelte" "kirin" "lake" "ls997" "m8" "m8d" "marlin"
"mata" "mermaid" "nash" "nx563j" "oneplus3" "payton" "pioneer" "polaris"
"river" "rs988" "sagit" "sailfish" "star2lte" "starlte" "twolip" "us996"
"voyager" "vs985" "vs995" "x2" "zl1"
```

Some of the devices, such as `h830` would fail with `variant="user"`, with the following error:
```
system/sepolicy/Android.mk:87: error: SELINUX_IGNORE_NEVERALLOWS := true cannot be used in user builds.
```
So, I just tested all the above with `variant="userdebug"`.

However, there are a few devices which failed. Their dependencies don't seem to be included:
```
"jasmine_sprout" # device/xiaomi/wayne-common/wayne.mk:64: error: _nic.PRODUCTS.[[device/xiaomi/jasmine/sprout/lineage_jasmine_sprout.mk]]: "device/xiaomi/sdm660-common/sdm660.mk" does not exist.
"jason #  device/xiaomi/jason/device.mk:180: error: _nic.PRODUCTS.[[device/xiaomi/jason/lineage_jason.mk]]: "device/xiaomi/sdm660-common/sdm660.mk" does not exist.
"shamu" # vendor/lineage/config/telephony.mk:21: error: _nic.PRODUCTS.[[device/moto/shamu/lineage_shamu.mk]]: "vendor/motorola/shamu/shamu-vendor.mk" does not exist.
"wayne"  # device/xiaomi/wayne-common/wayne.mk:64: error: _nic.PRODUCTS.[[device/xiaomi/wayne/lineage_wayne.mk]]: "device/xiaomi/sdm660-common/sdm660.mk" does not exist.
"z2_plus" # build/make/target/product/telephony_vendor.mk:24: error: _nic.PRODUCTS.[[device/zuk/z2/plus/lineage_z2_plus.mk]]: "device/zuk/z2_plus/device.mk" does not exist.
```
The json we use as the source for these dependencies seems to be missing some references: https://github.com/LineageOS/hudson/blob/master/updater/device_deps.json

**Comment by samueldr** [comment]
The xiaomi sdm660 devices, at least for one that is in their repos, but not in your list, all seem to be missing a couple deps.

The easy one first is that *The Muppets* repo for xiaomi is found on gitlab, DMCA reasons.

The other repo? I don't actually know where. It might be another organization that has it, but I have not been able to build a LineageOS `lavender` ROM using their tooling. I **assume** it's not ready.

For the non-xiaomi-sdm660 devices, weird.

**Comment by danielfullmer** [comment]
I actually already have a workaround for xiaomi being on gitlab:
https://github.com/danielfullmer/robotnix/blob/31f88a95523ea337e796062e4e911d589520deac/flavors/lineageos/update-devices.py#L128-L130

Still, I think 65/70 is pretty good! I wonder how many of them actually work!

**Comment by samueldr** [comment]
Confirmed,

```
Device product is 'H3123'.
Update requires 'sdm660'.
```

I'm not positive what all `board` values that are compatible would be, and if we can have a universal flashable zip with them. (That's an issue for later, not specific to this effort.)

**Comment by samueldr** [comment]
Haha, I should have looked before saying that. I only found that it was there yesterday, while I was looking for it for a couple days before!

**Comment by danielfullmer** [comment]
Hmm, it's unfortunate that buildEnv requires `openssl.dev`. Thanks for mentioning it.  I expect that other devices/flavors could have other impurities as well, so I might make a new config option to allow flavors to conditionally add packages to the environment.

Android 10 actually has some nice improvements in `soong` to sandbox the build with `nsjail` and avoid the host environment affecting the build. They currently ensure only certain host binaries are used, but so far they don't stop anything in the build from using host headers/libraries.
https://android.googlesource.com/platform/build/soong/+/refs/tags/android-10.0.0_r36/ui/build/sandbox_linux.go#150
Hopefully in Android 11 or 12 they will lock it down a bit more to make our job easier.

So, actually, `img` doesn't depend on `ota`, but rather, the `img` and `ota` targets both depend on `build.android`, which is the build step that takes hours.  Signing the build also shouldn't require rebuilding `build.android`, except for some cases where key fingerprints are inserted into the build (unfortunately F-Droid requires this).

**Comment by samueldr** [comment]
> I originally thought you needed [`openssl.dev`} because you were doing a bacon build

It's the kernel build itself that fails with it, just to be 100% clear.

I also forgot that I needed to pass a bogus `kernel.name` for the eval to succeed (in my `configuration.nix`).

**Comment by danielfullmer** [comment]
Thanks, that issue with `kernel.name` should hopefully be fixed with the latest commits.

**Comment by samueldr** [comment]
See

 * https://github.com/danielfullmer/robotnix/pull/8/commits/9433fe8c8a358a2682a4e7f3499d104d9e7ceb4e
 * https://github.com/danielfullmer/robotnix/pull/8/commits/4b7233d13f344c1d93247e390b1df3a72731efa3
 * https://github.com/danielfullmer/robotnix/pull/8/commits/139a3a8db632a1b2ff61dd827f0104c73897d8a1

**Comment by samueldr** [comment]
Can you add a list of TODOs to the PR description to see what's left to do?

I think that with the update script changes for  `--ref-type` and `--force` the non-nix hacks are taken care of.

Things I'm thinking that's left to do:

 * Maybe rewrite the history
 * Test with lineage-16.0, but I don't think lower than that has any use; though only ship json files for the latest version. Mostly as a curiosity, and maybe there are low-hanging fruits to pick.

I'm not saying there's nothing else :).

**Comment by samueldr** [comment]
Thank you!

**Comment by danielfullmer** [comment]
I think the reason some of the devices don't have the proper dependencies is because the `device_deps.json` from hudson is slightly out of date. It looks like someone periodically updates that json file: https://github.com/LineageOS/hudson/commit/8323e5742c8ed952776e464bb4278d946a5f173e

To make it work when this file is out of date, I think the recursive approach is right way to calculate the dependencies for a device.  Since we're already checking out these trees using `nix-prefetch-git`, hopefully it isn't too hard to do this. Starting from `android_<vendor>_<device>`, we'd follow the dependency graph while adding new dependencies using the `lineage.dependencies` file in each repo.  Not sure if I'll be able to work on this in the near future, since I'm up against some deadlines for school.

**Comment by samueldr** [comment]
I [made a WIP attempt at such a script](https://github.com/samueldr/robotnix/commit/cfbe5862220127c12bcdabc5c91cd2e9dd103373) (though in non-python) for a non-LineageOS, but LineageOS-based ROM.

One major thing I'd like to see in the LineageOS setup is to split all device dependencies in their own discrete files. The main idea being that it would be trivial to *somehow* point that dependencies script to a repository out of their organization and get all the dependencies slurped down. (A minor useless thing is that It also would make neater diffs when updating the trees...)

Though I don't want to push more support for more weird and random ROMs, that ROM does seem to push the envelope of the project a bit, which *could* be good to look at, without supporting. I'm thinking that the breakage it causes, compared to LineageOS, may point towards slightly wrong abstractions. I'm not confident in those assumptions though.

Additionally, looking into, but not supporting LineageOS-like ROMs will help users that may want to use robotnix to build the ROM of their choosing.

With that said, do your school stuff first! We can look into this more later.

**Comment by danielfullmer** [comment]
BTW, it is surprisingly looking quite close to being bit-for-bit reproducible. I built `kernel.android` twice and diff'ed the extracted `target_files`:
```
Binary files 1/BOOT/kernel and 2/BOOT/kernel differ
Binary files 1/SYSTEM/media/bootanimation.zip and 2/SYSTEM/media/bootanimation.zip differ
Binary files 1/VENDOR/lib/modules/br_netfilter.ko and 2/VENDOR/lib/modules/br_netfilter.ko differ
Binary files 1/VENDOR/lib/modules/gspca_main.ko and 2/VENDOR/lib/modules/gspca_main.ko differ
Binary files 1/VENDOR/lib/modules/mpq-adapter.ko and 2/VENDOR/lib/modules/mpq-adapter.ko differ
Binary files 1/VENDOR/lib/modules/mpq-dmx-hw-plugin.ko and 2/VENDOR/lib/modules/mpq-dmx-hw-plugin.ko differ
Binary files 1/VENDOR/lib/modules/msm_11ad_proxy.ko and 2/VENDOR/lib/modules/msm_11ad_proxy.ko differ
Binary files 1/VENDOR/lib/modules/rdbg.ko and 2/VENDOR/lib/modules/rdbg.ko differ
Binary files 1/VENDOR/lib/modules/test-iosched.ko and 2/VENDOR/lib/modules/test-iosched.ko differ
Binary files 1/VENDOR/lib/modules/ufs_test.ko and 2/VENDOR/lib/modules/ufs_test.ko differ
Binary files 1/VENDOR/lib/modules/wil6210.ko and 2/VENDOR/lib/modules/wil6210.ko differ
```

**Comment by samueldr** [comment]
This suspiciously looks like most of the unreproducibility is in the kernel build, and otherwise the bootanimation. What are the chances the bootanimation zip has timestamps in it?

**Comment by danielfullmer** [comment]
@samueldr That looks to be the issue for `bootanimation.zip`. Here's a selection from `diffoscope`:
```
├── part4/00479.png
│ ├── sng
│ │ @@ -23,15 +23,15 @@
│ │  }
│ │  tEXt {
│ │      keyword: "Creator";
│ │      text: "Adobe After Effects";
│ │  }
│ │  tEXt {
│ │      keyword: "date:create";
│ │ -    text: "2020-05-09T06:10:17+00:00";
│ │ +    text: "2020-05-09T06:44:14+00:00";
│ │  }
│ │  tEXt {
│ │      keyword: "date:modify";
│ │      text: "2017-01-18T15:50:26+00:00";
│ │  }
│ │  IMAGE {
│ │      pixels base64
```



I recently added https://github.com/danielfullmer/robotnix/commit/53a643334d5d1c38e76aa54ba88665b191e31a2f as well to fix kernel reproducibility for vanilla/grapheneos. But since the kernel build is integrated into the android build on `lineageos`, we'll have to add a patch or something. Hopefully the timestamp is the only issue for the lineageos kernel.

**Comment by danielfullmer** [comment]
The `target_files` for LineageOS `marlin` are now entirely bit-for-bit reproducible! Tested against af6221e63fb0dc33c2a242f03f4669781c5f5e71 using:
```
nix-build default.nix \
  --arg configuration '{device="pioneer"; flavor="lineageos";}' \
   -A build.android
```

The `ota` target is reproducible as well. Briefly tested `pioneer` reproducibility as well but it looks like the kernel still has some issue with the appended DTB not being consistent.

**Comment by samueldr** [comment]
If marlin has a single device tree, I wonder if pioneer's issue is of unstable ordering of files when concatenating/building them whole. I *think* pioneer has a couple devices and device trees.

**Comment by danielfullmer** [comment]
Having an unstable ordering of files was an issue I had for marlin, fixed with https://github.com/danielfullmer/robotnix/commit/af6221e63fb0dc33c2a242f03f4669781c5f5e71
But apparently that wasn't sufficient for pioneer, which maybe gets its list of device trees differently.

**Comment by Atemu** [comment]
I finally found the time to check out you guys' work and I'm blown away, you rock!

I needed to to a tiny bit of tweaking to make it build for cheeseburger which is not officially supported on LOS17.1 but then it just... worked.  
With just two attributes added to the config attrset I also had an image with MicroG and F-droid ready to go, that's the Nix experience!

Because I needed to do modify the repos, I also had to use update-devices.py a few times which takes forever. 
Here's to change that: #21 :)

**Comment by Atemu** [comment]
I think I'm going to tackle merging and cleaning up the update scripts next. What else needs to be done to get this PR into master?

**Comment by danielfullmer** [comment]
@Atemu It's great to hear that it worked for you! I'll take a look at your PR hopefully tomorrow.

As far as merging:  I'll try to merge it into master soon. I'll just need to write some documentation describing LineageOS support as "experimental" and note that some modules (like the updater) might not work correctly with LineageOS yet. 

I originally wanted to get the LineageOS updater working. That by itself shouldn't be too hard, but the harder part would be refactoring the robotnix code to nicely support another updater, with different metadata and OTA directory structure. At the moment some of the updater / OTA aspects that are specific to the current vanilla / GrapheneOS updater are hardcoded into `modules/release.nix`.  I took an earlier attempt at this but never quite got it into a state that I was happy with.  However, I don't think that should block merging LineageOS into master.  

We'll need to figure out the status of AVB (Android Verified Boot) in LineageOS (is it disabled for every device?).  I also need to look into how APEX packages are used in LineageOS: https://android.googlesource.com/platform/system/apex/+/refs/heads/master/docs/README.md
APEX is a mechanism that Android 10 has to update certain components of the OS independently.  If the APEX updater is used, we also need to generate keys for the APEX packages. Otherwise, they get signed with a default key that is publicly known (like `test-keys`). However, "APEX updating" can be disabled as well. IIRC, when I built a LineageOS ROM using robotnix it looked like APEX updating was enabled, but when I grabbed a LineageOS build from their site, it looked like this was disabled.  So, perhaps there is some additional configuration that robotnix is missing (maybe set in their CI configuration)?

**Comment by danielfullmer** [comment]
Just updated the source, built, and briefly tested on my Pixel 1 with `microg` and `fdroid` support enabled.

Merged into master, along with some documentation describing LineageOS support as "experimental".  I should have done this earlier since maintaining a long-running branch like this isn't too convenient.  There's still a lot of potential things we could do for better LineageOS support, including the remaining tasks at the top of this PR.

Thanks @samueldr and @Atemu for your help!

**Pull request merged**
